# Generated by Django 3.2.6 on 2023-07-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('marks', models.TextField()),
                ('date_of_admission', models.DateField(auto_now_add=True)),
                ('grade', models.CharField(choices=[('sp', 'Special Grade'), ('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'F0Rth')], max_length=3)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'db_table': 'student',
            },
        ),
    ]
